# Generated by Django 5.1 on 2024-09-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_budget_end_date_budget_month_budget_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=9),
        ),
    ]
